# Generated by Django 5.2.17 on 2026-10-05 08:16

import apps.workspaces.logo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='logo',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.workspaces.logo.logo_upload_to),
        ),
    ]
